[package]
name = "rand-generator-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
falco_plugin = { git = "https://github.com/falcosecurity/plugin-sdk-rs" }
rand = { version = "0.8.5"}
